### ISSUE TITLE
Document support status of cascading replication

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/storagegrid-117#39]
### Page URL

https://docs.netapp.com/us-en/storagegrid-117/admin/grid-federation-compare-cgr-to-cloudmirror.html

### Page title

Compare cross-grid replication and CloudMirror replication

### Summary

Sometimes users want to replicate in a cascading manner, e.g. G1->G2->G3.

The documentation doesn't seem to have this information.

- Is cascading replication of the same bucket supported for Cross-Grid Replication (G1-(CGR)->G2-(CGR)->G3)?
- The same for Cloud Mirror - (G1-(CM)->G2-(CM)->G3)
- How about mixed; G1-(CGR)->G2-(CM)->G3 _or_ G1-(CM)->G2-(CGR)->G3?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Thanks @scaleoutsean for submitting these questions. I'll consult with the StorageGRID team and then update you here.

**Comment by netapp-pcarriga** [comment]
@scaleoutsean Engineering confirmed that a documentation update is not required because the information is available in [TR-4982-Grid Federation and Cross Grid Replication ](https://fieldportal.netapp.com/s/article/tr4982grid-federation-and-cross-grid-replication-1698408234134). You need a Field Portal account to access this technical report.
